QLTTDT/Controllers/AllTopicController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QLTTDT.Data;
using QLTTDT.Services;
using QLTTDT.ViewModels;

namespace QLTTDT.Controllers
{
    public class AllTopicController : Controller
    {
        private QLTTDTDbContext _context;
        public AllTopicController(QLTTDTDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index(string? searchString)
        {
            int? userId = GetUserId();
            var tmp = _context.ChuDes.Select(i => i);
            if (!String.IsNullOrEmpty(searchString))
            {
                tmp = tmp.Where(i => i.TenChuDe.ToUpper()
                .Contains(searchString.ToUpper()));
            }
            var topicCards = tmp.Select(i => 
            new TopicCard {
                MaChuDe = i.MaChuDe,
                TenChuDe = i.TenChuDe,
                MoTa = i.MoTa,
                UrlAnhChuDe = i.UrlAnhChuDe,
                SoKhoaHocDaDangKi = (userId == null) ? 0 : _context.DangKiKhoaHocs
                .Include(j => j.MaKhoaHocNavigation)
                .Count(j => j.MaKhoaHocNavigation.MaChuDe == i.MaChuDe && j.MaHocVien == userId),
            });
            return View(await topicCards.ToListAsync());
        }
        public async Task<IActionResult> Details(string? topicSlug, int? topicId, string? searchString)
        {
            var slugCheck = new SlugCheck(_context);
            if(!await slugCheck.CheckTopicSlug(topicSlug, topicId))
            {
                return NotFound();
            }
            int? userId = GetUserId();
            var chuDe = await _context.ChuDes.FirstOrDefaultAsync(m => m.MaChuDe == topicId);
            if (chuDe == null)
            {
                return NotFound();
            }
            var khoaHocs = _context.KhoaHocs
                .Include(i => i.MaCapDoNavigation)
                .Where(i => i.MaChuDe == chuDe.MaChuDe)
                .Select(i => new CourseCard
                {
                    MaKhoaHoc = i.MaKhoaHoc,
                    TenKhoaHoc = i.TenKhoaHoc,
                    CapDo = i.MaCapDoNavigation.TenCapDo,
                    MoTa = i.MoTa,
                    UrlAnhKhoaHoc = i.UrlAnh,
                    DaDangKi = (userId == null) ? false : _context.DangKiKhoaHocs
                    .Any(j => j.MaKhoaHoc == i.MaKhoaHoc && j.MaHocVien == userId),
                });

            if(!String.IsNullOrEmpty(searchString))
            {
                searchString = searchString.ToUpper();
                khoaHocs = khoaHocs.Where(i => i.TenKhoaHoc.ToUpper().Contains(searchString)
                || i.CapDo.ToUpper().Contains(searchString));
            }

            var topicDesc = new TopicDescription
            {
                MaChuDe = chuDe.MaChuDe,
                TenChuDe = chuDe.TenChuDe,
                MoTa = chuDe.MoTa,
                UrlAnhChuDe = chuDe.UrlAnhChuDe,
                DanhSachKhoaHoc = await khoaHocs.ToListAsync(),
                SoKhoaHocDaDangKi = (userId == null) ? 0 : _context.DangKiKhoaHocs
                .Count(j => j.MaKhoaHocNavigation.MaChuDe == chuDe.MaChuDe && j.MaHocVien == userId)
            };

            return View(topicDesc);
        }
        private int? GetUserId()
        {
            return Convert.ToInt32(HttpContext.User.FindFirst(ClaimTypes.NameIdentifier)?.Value.ToString());
        }
    }
}

QLTTDT/Controllers/CourseController.cs
using System.Security.Claims;
using AspNetCoreGeneratedDocument;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QLTTDT.Data;
using QLTTDT.Models;
using QLTTDT.Services;
using QLTTDT.ViewModels;

namespace QLTTDT.Controllers
{
    public class CourseController : Controller
    {
        private QLTTDTDbContext _context;
        public CourseController(QLTTDTDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index(string? topicSlug, int? topicId, string? courseSlug, int? courseId)
        {
            var slugCheck = new SlugCheck(_context);
            if (!await slugCheck.CheckTopicCourseSlug(topicSlug, topicId, courseSlug, courseId))
            {
                return NotFound();
            }
            var khoaHoc = await _context.KhoaHocs
                .FirstOrDefaultAsync(m => m.MaKhoaHoc == courseId);
            if (khoaHoc == null)
            {
                return NotFound();
            }
            int? userId = GetUserId();
            var courseDesc = new CourseDescription
            {
                MaKhoaHoc = khoaHoc.MaKhoaHoc,
                TenKhoaHoc = khoaHoc.TenKhoaHoc,
                MaCapDo = khoaHoc.MaCapDo,
                MaChuDe = khoaHoc.MaChuDe,
                MaGiangVien = khoaHoc.MaGiangVien,
                MoTa = khoaHoc.MoTa,
                HocPhi = khoaHoc.HocPhi,
                SoLuongHocVienToiDa = khoaHoc.SoLuongHocVienToiDa,
                ThoiGianKhaiGiang = khoaHoc.ThoiGianKhaiGiang,
                ThoiGianCompute = khoaHoc.ThoiGianCompute,
                UrlAnh = khoaHoc.UrlAnh,
                TenCapDo = (await _context.CapDos.FirstOrDefaultAsync(i => i.MaCapDo == khoaHoc.MaCapDo))?.TenCapDo,
                TenChuDe = (await _context.ChuDes.FirstOrDefaultAsync(i => i.MaChuDe == khoaHoc.MaChuDe))?.TenChuDe,
                TenGiangVien = (await _context.NguoiDungs.FirstOrDefaultAsync(i => i.MaNguoiDung == khoaHoc.MaGiangVien))?.HoVaTen,
                SoLuongHocVienDangKi = await _context.DangKiKhoaHocs.CountAsync(i => i.MaKhoaHoc == khoaHoc.MaKhoaHoc),
                DaDangKi = (userId == null) ? false : await _context.DangKiKhoaHocs
                .AnyAsync(i => i.MaKhoaHoc == khoaHoc.MaKhoaHoc && i.MaHocVien == userId),
                TienDo = await GetProgress(khoaHoc, userId),
            };
            return View(courseDesc);
        }

        [Authorize(Roles = "HocVien,Admin")]
        [HttpPost]
        public async Task<IActionResult> Index(string topicSlug, int? topicId, string courseSlug, int? courseId, bool noUse)
        {
            var slugCheck = new SlugCheck(_context);
            if (!await slugCheck.CheckTopicCourseSlug(topicSlug, topicId, courseSlug, courseId))
            {
                return NotFound();
            }
            var khoaHoc = await _context.KhoaHocs.FirstOrDefaultAsync(m => m.MaKhoaHoc == courseId);
            if (khoaHoc == null)
            {
                return NotFound();
            }
            int? userId = GetUserId();
            var validation = new ValidCheck(_context);
            if (userId != null && courseId != null && await validation.IsRegisterCourseVaild(userId, courseId))
            {
                var dkkh = await _context.DangKiKhoaHocs.IgnoreQueryFilters().FirstOrDefaultAsync(i => i.MaHocVien == userId && i.MaKhoaHoc == courseId && i.DaHuy == true);
                if (dkkh != null)
                {
                    dkkh.DaHuy = false;
                    dkkh.HocPhi = khoaHoc.HocPhi;
                    dkkh.ThoiGianDangKi = DateTime.Now;
                    try
                    {
                        _context.Update(dkkh);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException ex)
                    {
                        return BadRequest(ex.Message);
                    }
                }
                else
                {
                    var register = new DangKiKhoaHoc
                    {
                        MaHocVien = (int)userId,
                        MaKhoaHoc = (int)courseId,
                        HocPhi = khoaHoc.HocPhi,
                    };
                    _context.Add(register);
                    await _context.SaveChangesAsync();
                }
            }
            return RedirectToAction("Index", new { topicSlug, topicId, courseSlug, courseId });
        }
        private async Task<int> GetProgress(KhoaHoc khoaHoc, int? userId)
        {
            if (userId == null) return 0;
            var dkkh = await _context.DangKiKhoaHocs.FirstOrDefaultAsync(i => i.MaKhoaHoc == khoaHoc.MaKhoaHoc && i.MaHocVien == userId);
            if (dkkh == null) return 0;
            return dkkh.TienDo;
        }
        [Authorize(Roles = "HocVien,Admin")]
        [HttpPost]
        public async Task<IActionResult> IncreaseProgress(string topicSlug, int? topicId, string courseSlug, int? courseId)
        {
            var slugCheck = new SlugCheck(_context);
            if (!await slugCheck.CheckTopicCourseSlug(topicSlug, topicId, courseSlug, courseId))
            {
                return NotFound();
            }
            var khoaHoc = await _context.KhoaHocs.FirstOrDefaultAsync(m => m.MaKhoaHoc == courseId);
            if (khoaHoc == null)
            {
                return NotFound();
            }
            int? userId = GetUserId();
            var dkkh = await _context.DangKiKhoaHocs.FirstOrDefaultAsync(i => i.MaKhoaHoc == khoaHoc.MaKhoaHoc && i.MaHocVien == userId);
            if (dkkh != null)
            {
                if (ValidCheck.IsProgressValid(dkkh.TienDo + 20))
                {
                    dkkh.TienDo += 20;
                }
                try
                {
                    _context.Update(dkkh);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException ex)
                {
                    return BadRequest(ex.Message);
                }
            }
            return RedirectToAction("Index", new { topicSlug, topicId, courseSlug, courseId });
        }
        [Authorize(Roles = "HocVien,Admin")]
        [HttpPost]
        public async Task<IActionResult> CancellCourse(string topicSlug, int? topicId, string courseSlug, int? courseId)
        {
            if (courseId == null)
            {
                return NotFound();
            }
            var khoaHoc = await _context.KhoaHocs.FirstOrDefaultAsync(m => m.MaKhoaHoc == courseId);
            if (khoaHoc == null)
            {
                return NotFound();
            }
            int? userId = GetUserId();
            var dkkh = await _context.DangKiKhoaHocs.FirstOrDefaultAsync(i => i.MaKhoaHoc == khoaHoc.MaKhoaHoc && i.MaHocVien == userId);
            if (dkkh != null)
            {
                try
                {
                    dkkh.DaHuy = true;
                    _context.Update(dkkh);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException ex)
                {
                    return BadRequest(ex.Message);
                }
            }
            return RedirectToAction("Index", new { topicSlug, topicId, courseSlug, courseId });
        }
        [Authorize(Roles = "HocVien,Admin")]
        public async Task<IActionResult> RegisteredCourse()
        {
            int? userId = GetUserId();
            var courses = await _context.KhoaHocs
                .Include(i => i.MaChuDeNavigation)
                .Include(i => i.MaCapDoNavigation)
                .Where(i => _context.DangKiKhoaHocs.Any(j => j.MaKhoaHoc == i.MaKhoaHoc && j.MaHocVien == userId))
                .Select(i => new CourseCardWithTopic
                {
                    MaChuDe = i.MaChuDe,
                    TenChuDe = i.MaChuDeNavigation.TenChuDe,
                    CapDo = i.MaCapDoNavigation.TenCapDo,
                    MaKhoaHoc = i.MaKhoaHoc,
                    MoTa = i.MoTa,
                    TenKhoaHoc = i.TenKhoaHoc,
                    UrlAnhKhoaHoc = i.UrlAnh,
                })
                .AsSplitQuery()
                .ToListAsync();
            return View(courses);
        }
        [Authorize(Roles = "HocVien,Admin")]
        public async Task<IActionResult> LearningCourse()
        {
            int? userId = GetUserId();
            var courses = await _context.KhoaHocs
                .Include(i => i.MaChuDeNavigation)
                .Include(i => i.MaCapDoNavigation)
                .Where(i => i.ThoiGianKhaiGiang <= DateTime.Now && _context.DangKiKhoaHocs
                .Any(j => j.MaKhoaHoc == i.MaKhoaHoc && j.MaHocVien == userId
                && j.TienDo >= 0 && j.TienDo < 100))
                .Select(i => new CourseCardWithTopic
                {
                    MaChuDe = i.MaChuDe,
                    TenChuDe = i.MaChuDeNavigation.TenChuDe,
                    CapDo = i.MaCapDoNavigation.TenCapDo,
                    MaKhoaHoc = i.MaKhoaHoc,
                    MoTa = i.MoTa,
                    TenKhoaHoc = i.TenKhoaHoc,
                    UrlAnhKhoaHoc = i.UrlAnh,
                })
                .AsSplitQuery()
                .ToListAsync();
            return View(courses);
        }
        [Authorize(Roles = "HocVien,Admin")]
        public async Task<IActionResult> CompletedCourse()
        {
            int? userId = GetUserId();
            var courses = await _context.KhoaHocs
                .Include(i => i.MaChuDeNavigation)
                .Include(i => i.MaCapDoNavigation)
                .Where(i => i.ThoiGianKhaiGiang <= DateTime.Now && _context.DangKiKhoaHocs
                .Any(j => j.MaKhoaHoc == i.MaKhoaHoc && j.MaHocVien == userId
                && j.TienDo == 100))

QLTTDT/Views/Course/CompletedCourse.cshtml
@model IEnumerable<CourseCardWithTopic>;
@{
	ViewData["Title"] = "Khoá học đã hoàn thành";
}

<div class="template__homepage-content">
	<div class="container">
		<div class="course-grid">
			@foreach (var item in Model)
			{
				<a class="course-card"
				   asp-controller="Course"
				   asp-action="Index"
				   asp-route-topicSlug="@StrToSlug.Convert(item.TenChuDe)"
				   asp-route-topicId="@item.MaChuDe"
				   asp-route-courseSlug="@StrToSlug.Convert(item.TenKhoaHoc)"
				   asp-route-courseId="@item.MaKhoaHoc">

					@if (item.UrlAnhKhoaHoc != null)
					{
						<img src="~/images/@item.UrlAnhKhoaHoc" alt="Ảnh khoá học" class="border-bottom" />
					}
					else
					{
						<img src="~/Resource/Couratest-course.png" alt="Ảnh khoá học" class="border-bottom" />
					}

					<div class="d-flex flex-column box-padding-10 row-gap-1 course-content">
						<div class="break-word min-height-custom-1 line-clamp-2">
							<h3>@Html.DisplayFor(modelItem => item.TenKhoaHoc)</h3>
						</div>
						<div class="break-word min-height-custom-2 line-clamp-4">
							@Html.DisplayFor(modelItem => item.MoTa)
						</div>
					</div>

					<div class="course-tags-wrapper">
						<div class="course-level">@Html.DisplayFor(modelItem => item.CapDo)</div>
					</div>
				</a>
			}
		</div>
	</div>
</div>

QLTTDT/Views/Course/Index.cshtml
@model CourseDescription;
@{
	ViewData["Title"] = "Khoá học";
}

<div class="course-desc-container">
	<div class="course-desc-hero">
		<div class="course-desc-details">
			<h1 class="course-desc-title">
				<strong>
					@Html.DisplayFor(m => m.TenKhoaHoc)
				</strong>
			</h1>
			<div class="course-desc-subtitle">
				<strong>Chủ đề:</strong>
				<a asp-controller="AllTopic" asp-action="Details"
				asp-route-topicSlug="@StrToSlug.Convert(Model.TenChuDe!)"
				asp-route-topicId="@Model.MaChuDe" class="tabs__link--tertiary">
					@Html.DisplayFor(m => m.TenChuDe)
				</a>
			</div>

			<div class="course-desc-item">
				<strong class="course-desc-label">Giảng viên:</strong>
				<span class="course-desc-value">@Html.DisplayFor(m => m.TenGiangVien)</span>
			</div>

			<div class="course-desc-item">
				<strong class="course-desc-label">Học Phí:</strong>
				<span class="course-desc-value-highlight">
					@string.Format("{0:N0} ₫", Model.HocPhi)
				</span>
			</div>

			<div class="course-desc-item">
				<strong class="course-desc-label">Thời Gian Khai Giảng:</strong>
				<span class="course-desc-value">@Model.ThoiGianCompute</span>
			</div>


			<div class="course-desc-item">
				<strong class="course-desc-label">Mô Tả:</strong>
				<div class="course-desc-description">@Html.DisplayFor(m => m.MoTa)</div>
			</div>

			<div class="course-desc-actions">
				@if (Model.DaDangKi)
				{
					if (DateTime.UtcNow < Model.ThoiGianKhaiGiang)
					{
						<form asp-controller="Course" asp-action="CancellCourse"
						asp-route-topicSlug="@StrToSlug.Convert(Model.TenChuDe!)"
						asp-route-topicId="@Model.MaChuDe"
						asp-route-courseSlug="@StrToSlug.Convert(Model.TenKhoaHoc)"
						asp-route-courseId="@Model.MaKhoaHoc" method="post" class="course-desc-form">
							<input type="submit" value="Huỷ đăng kí" class="course-desc-button" />
						</form>
					}
					else
					{
						<div>
							<div>
								<strong>Tiến độ đã học:</strong>
								@Html.DisplayFor(model => model.TienDo)%
							</div>
						</div>
						if (Model.TienDo < 100)
						{
							<form asp-controller="Course" asp-action="IncreaseProgress"
							asp-route-topicSlug="@StrToSlug.Convert(Model.TenChuDe!)"
							asp-route-topicId="@Model.MaChuDe"
							asp-route-courseSlug="@StrToSlug.Convert(Model.TenKhoaHoc)"
							asp-route-courseId="@Model.MaKhoaHoc" method="post" class="course-desc-form">
								<input type="submit" value="Tăng 20% tiến độ" class="course-desc-button" />
							</form>
						}
					}
				}
				else if (Model.SoLuongHocVienDangKi < Model.SoLuongHocVienToiDa)
				{
					<form asp-controller="Course" asp-action="Index"
					asp-route-topicSlug="@StrToSlug.Convert(Model.TenChuDe!)"
					asp-route-topicId="@Model.MaChuDe"
					asp-route-courseSlug="@StrToSlug.Convert(Model.TenKhoaHoc)"
					asp-route-courseId="@Model.MaKhoaHoc" method="post" class="course-desc-form">
						<input type="hidden" name="noUse" />
						<input type="submit" value="Đăng kí khoá học" class="course-desc-button" />
					</form>
				}
				else
				{
					<div>
						<strong>
							Số lượng học viên được đăng kí đã đạt giới hạn.
						</strong>
					</div>
				}
			</div>

			<div class="course-desc-stats">
				<span>@Html.DisplayFor(m => m.SoLuongHocVienDangKi) / @Html.DisplayFor(m => m.SoLuongHocVienToiDa) học viên</span>
			</div>
		</div>
		<div class="course-desc-course-image">
			@if(Model.UrlAnh != null)
			{
				<img src="~/images/@Model.UrlAnh" alt="Ảnh bìa khóa học" />
			}
			else
			{
				<img src="~/Resource/Couratest-course.png" alt="Ảnh bìa khóa học" />
			}
		</div>
	</div>
</div>

QLTTDT/Views/Course/LearningCourse.cshtml
@model IEnumerable<CourseCardWithTopic>;
@{
	ViewData["Title"] = "Khoá học đang học";
}

<div class="template__homepage-content">
	<div class="container">
		<div class="course-grid">
			@foreach (var item in Model)
			{
				<a class="course-card"
				   asp-controller="Course"
				   asp-action="Index"
				   asp-route-topicSlug="@StrToSlug.Convert(item.TenChuDe)"
				   asp-route-topicId="@item.MaChuDe"
				   asp-route-courseSlug="@StrToSlug.Convert(item.TenKhoaHoc)"
				   asp-route-courseId="@item.MaKhoaHoc">

					@if (item.UrlAnhKhoaHoc != null)
					{
						<img src="~/images/@item.UrlAnhKhoaHoc" alt="Ảnh khoá học" class="border-bottom" />
					}
					else
					{
						<img src="~/Resource/Couratest-course.png" alt="Ảnh khoá học" class="border-bottom" />
					}

					<div class="d-flex flex-column box-padding-10 row-gap-1 course-content">
						<div class="break-word min-height-custom-1 line-clamp-2">
							<h3>@Html.DisplayFor(modelItem => item.TenKhoaHoc)</h3>
						</div>
						<div class="break-word min-height-custom-2 line-clamp-4">
							@Html.DisplayFor(modelItem => item.MoTa)
						</div>
					</div>

					<div class="course-tags-wrapper">
						<div class="course-level">@Html.DisplayFor(modelItem => item.CapDo)</div>
					</div>
				</a>
			}
		</div>
	</div>
</div>

QLTTDT/Views/Course/RegisteredCourse.cshtml
@model IEnumerable<CourseCardWithTopic>;
@{
	ViewData["Title"] = "Khoá học đã đăng ký";
}

<div class="template__homepage-content">
	<div class="container">
		<div class="course-grid">
			@foreach (var item in Model)
			{
				<a class="course-card"
				   asp-controller="Course"
				   asp-action="Index"
				   asp-route-topicSlug="@StrToSlug.Convert(item.TenChuDe)"
				   asp-route-topicId="@item.MaChuDe"
				   asp-route-courseSlug="@StrToSlug.Convert(item.TenKhoaHoc)"
				   asp-route-courseId="@item.MaKhoaHoc">

					@if (item.UrlAnhKhoaHoc != null)
					{
						<img src="~/images/@item.UrlAnhKhoaHoc" alt="Ảnh khoá học" class="border-bottom" />
					}
					else
					{
						<img src="~/Resource/Couratest-course.png" alt="Ảnh khoá học" class="border-bottom" />
					}

					<div class="d-flex flex-column box-padding-10 row-gap-1 course-content">
						<div class="break-word min-height-custom-1 line-clamp-2">
							<h3>@Html.DisplayFor(modelItem => item.TenKhoaHoc)</h3>
						</div>
						<div class="break-word min-height-custom-2 line-clamp-4">
							@Html.DisplayFor(modelItem => item.MoTa)
						</div>
					</div>

					<div class="course-tags-wrapper">
						<div class="course-level">@Html.DisplayFor(modelItem => item.CapDo)</div>
					</div>
				</a>
			}
		</div>
	</div>
</div>